export const products = [
    {
        id: 1,
        name: "Midnight Oud Royale",
        price: 12999,
        image: { uri: "https://aroma-luxe-static-lwf6ktjpy-mishra-coders-projects.vercel.app/assets/src/assets/perfumes/5k_7b55f6f3-7569-44da-9b21-5f1acb38c378.9a9ec98bd8a184e59928a9f531d0c582.jpeg" },
        description: "A deep, mysterious blend of precious agarwood and rare resins. This fragrance is the epitome of luxury, designed for those who command respect and leave a lasting impression.",
        category: "Oriental",
        type: "Parfum",
        notes: { top: ["Saffron", "Pink Pepper"], middle: ["Oud Wood", "Bulgarian Rose"], base: ["Sandalwood", "Amber", "Leather"] },
        occasions: ["party", "date", "festival"],
        timeOfDay: ["night"],
        seasons: ["winter", "all"],
        strength: 5,
        profile: "strong"
    },
    {
        id: 2,
        name: "Velvet Rose Elixir",
        price: 8499,
        image: { uri: "https://aroma-luxe-static-lwf6ktjpy-mishra-coders-projects.vercel.app/assets/src/assets/perfumes/A6mrGrFx_4f49e7e57a6e49b8aa84bf2f2e3a6573.70a5ad59839da52512f9e69118cbb083.jpg" },
        description: "An opulent floral masterpiece combining damask rose with rich textures of clove and decadent praline. A sophisticated scent that wraps you in a blanket of elegance.",
        category: "Floral",
        type: "EDP",
        notes: { top: ["Cloves", "Lemon"], middle: ["Damask Rose", "Peony"], base: ["Praline", "Agarwood"] },
        occasions: ["date", "party", "festival"],
        timeOfDay: ["night"],
        seasons: ["all"],
        strength: 4,
        profile: "sweet"
    },
    {
        id: 3,
        name: "Aqua Allegoria Luxe",
        price: 6499,
        image: { uri: "https://aroma-luxe-static-lwf6ktjpy-mishra-coders-projects.vercel.app/assets/src/assets/perfumes/Davidoff-cool-water-parfum-Men.jpg.7d289f6ada99ff80fe3f0ab86c62ab9b.webp" },
        description: "A revitalizing burst of citrus and aquatic notes. Inspired by Mediterranean mornings, this fresh fragrance is clean, light, and undeniably premium.",
        category: "Fresh",
        type: "EDT",
        notes: { top: ["Bergamot", "Grapefruit"], middle: ["Sea Salt", "Lavender"], base: ["White Musk", "Cedar"] },
        occasions: ["college", "gym", "office"],
        timeOfDay: ["day"],
        seasons: ["summer", "all"],
        strength: 2,
        profile: "fresh"
    },
    {
        id: 4,
        name: "Emperor Aventus Noir",
        price: 15999,
        image: { uri: "https://aroma-luxe-static-lwf6ktjpy-mishra-coders-projects.vercel.app/assets/src/assets/perfumes/HugoBossBottledTonicEDTForMen100ml.9924b4409c35df42d5d9255fd0a705c4.webp" },
        description: "The ultimate power scent. Featuring a bold combination of fruity top notes and a rich, smoky base. Truly the king of modern fragrances for the elite.",
        category: "Woody",
        type: "EDP",
        notes: { top: ["Pineapple", "Black Currant"], middle: ["Birch", "Patchouli"], base: ["Musk", "Oakmoss", "Vanilla"] },
        occasions: ["office", "date", "festival"],
        timeOfDay: ["day", "night"],
        seasons: ["winter", "all"],
        strength: 4,
        profile: "mild"
    }
];
